name: Code Check（ESLint, Prettier, Vitest）

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.11.0]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint check
        run: npm run lint

  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.11.0]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run format check
        run: npm run format:check

  test-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23.11.0]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run test check
        run: npm run test
